import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { WalletSelectorContextProvider } from "../components/near/index";
import '@mantine/core/styles.css';
import { MantineProvider } from '@mantine/core';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider >
          <WalletSelectorContextProvider>

            {children}
          </WalletSelectorContextProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
